import Head from "next/head";
import React from "react";
import Nav from "./headerItems/Nav";
import styles from "/styles/Home.module.css";

const Header = () => {
  return (
    <header className={styles.header}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Nav />
   
    </header>
  );
};

export default Header;
